### ISSUE TITLE
addpoints

### ISSUE THREAD

**Issue by bob-skowron** [jasonwalker80/cse427s#58]
With lat/long you can only go up to +-90/180. i think we need to adjust addpoints to handle this.

**Comment by bob-skowron** [comment]
I think something like this will work:

def addPoints(p1,p2):
	# we need to be careful here, if we go over +-180/90 we need to restart
	add_lat = p1[0] + p2[0] 
	add_lon = p1[1] + p2{1]
	
	# compute new latitude
	if add_lat > 90
		lat = 90 - (add_lat % 90) #if we go over 90 (N pole) we count back down
		add_lon += 180 # we also just moved around the globe so need to move longitude
	else if add_lat < -90
		lat = -((p1[0] + p2[0]) % 90) # go over S pole, count back down but negative
		add_lon += 180 # also go around the world longitude
	else
		lat = add_lat
		
	# compute new longitude
	if add_lon > 180
		add_lon = -180 + (add_lon % 180) # start counting down from -180
	else if add_lon < -180
		add_lon = 180 + (add_lon % -180) # count down from 180
	else
		lon = add_lon
		
	return (lat, lon)

**Comment by bob-skowron** [comment]
**Line from project doc**: Note, that the addPoints function will be used to compute the new cluster centers.  As we are working with spatial data given as latitude-longitude pairs implementing this function
in a meaningful way will need some thought!

interesting thing is though, when we find the mean, we don't want to do this.... the regular sum then divide would give you the correct center. maybe she is just referring to the fact that it is a pair??

**Comment by bob-skowron** [comment]
Actually, i figured out the right answer. we need to think of the coordinates as vectors. so when you add, the correct way to do so would be to /2 on each to normalize back to the circle
def addPoints(p1,p2):
return ((p1[0] + p2[0])/2,(p1[1] + p2{1])/2)

think about a a point at (0, 0) and (90,0). We want the sum of those vectors to be (45,0) i'm pretty sure, not (90,0). Or two points at (45,45) -> answer should be (45, 45) not (90, 90)

Thinking in 3 point space - (0,0), (90, 0), (0,180). Is the right answer (30, 60)? or (45, 90)? I'm pretty sure the latter

Then, when doing the k-means i dont think there is any division. The addition of all the vectors works out to be the mean

One last thing to think about. Points (0, -160) and (0, 20). Is the answer (0, 110) or (0, -70)?

**Comment by bob-skowron** [comment]
OK, one last thought... extending on the above, we may have to convert from polar coordinates to cartesian, add then convert back...

**Comment by keon6kim** [comment]
Sorry about late response, I was not getting any notifications about this.

Anyways, I don't think we even need to use the addPoints() function
I am just using geopy to calculate the distances btw 2 (lat,long) points. 

Right now I am just adding up all the latitude ant longitude values like a SumReducer would and then dividing by the number of points in each cluster.

**Comment by keon6kim** [comment]
Besides that, 
I just committed what it seems like a somewhat finalized version of the k-means algorithm under
"/final_project/spark"


My only 1 concern is that I am outputing the GreatCircleDistance in miles. I need to figure out how that relates to convergeDist = 0.1 , in other words, I don't really know what units 0.1 is in.

Other than that, I tested a few small time cases and the code seems to work.


NOTE: (I'm referring to parts as I categorized in my code)
Part 1 of the program really depends on the format of the data that is going to be used, so I think it would be better written by the key user who really understands the format of the data.

Part 2. (finding the correct k value) This part I didn't write anything since it really depends on what we are trying to accomplish with the data.

Part 1 and Part 2 should both be pretty simple and quick to write I believe.

**Comment by keon6kim** [comment]
@bskowron23 
Oh I do see now that I am still adding points blindly, I changed the code to take account of your version of addPoints.

I commented the part where I actually call addPoints() during a transformation of a RDD, just in case my syntax is wrong.

**Comment by bob-skowron** [comment]
Mine is still wrong, but I'll write a correct one tonight and merge the two

**Comment by bob-skowron** [comment]
I just updated with what i think is the correct logic. Open another issue if anyone thinks it's off.
